[package]
name = "zed-kafka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
path = "src/lib.rs"

[dependencies]
actix-web = { version = "4.4.1", default-features = false }
rdkafka = { version = "0.36.0", features = ["tokio"] }
tokio = "1.35.1"
